# Generated by Django 5.0 on 2023-12-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dimension_usuarios',
            new_name='DimensionUsuarios',
        ),
    ]
